Algoritmo "AtividadePrática9"

Procedimento produto
Var
   aux: inteiro
Inicio
   aux <- a * b
   res <- aux
FimProcedimento

Var
   a, b, res: Inteiro
Inicio
   EscrevaL("------------------")
   EscrevaL("O PRODUTO DE A x B")
   EscrevaL("------------------")
   EscrevaL("")
   Escreva("Digite o valor de A: ")
   Leia(a)
   Escreva("Digite o valor de B: ")
   Leia(b)
   produto
   Escreva("O produto de ", a, " x ", b, " é igual a: ", res)
Fimalgoritmo