Algoritmo "AtividadePratica11"

funcao produto: inteiro
var
   aux: inteiro
inicio
   aux <- a * b
   retorne aux
fimFuncao

Var
   a, b, res: inteiro
Inicio
   EscrevaL("--------------------------")
   EscrevaL("PROGRAMA: PRODUTO DE A x B")
   EscrevaL("--------------------------")
   EscrevaL()
   Escreva("Digite o valor de A: ")
   Leia(a)
   Escreva("Digite o valor de B: ")
   Leia(b)
   res <- produto
   escreva("O produto de A x B é: ",res)
Fimalgoritmo