Algoritmo "AtividadePratica1"

Var
   numero1, numero2, numero3, soma: inteiro
   media: real
Inicio
      numero1 <- 10
      numero2 <- 5
      numero3 <- 2
      soma <- numero1 + numero2 + numero3
      media <- (numero1 + numero2 + numero3) / 3
      escrevaL ("Número 1: ", numero1)
      escrevaL ("Número 2: ", numero2)
      escrevaL ("Número 3: ", numero3)
      escrevaL ("A soma entre eles é de: ", soma)
      escrevaL ("A média entre eles é de: ", media)
Fimalgoritmo
