Algoritmo "AtividadePratica2"

Var
   soma: inteiro
   media: real
Inicio
      soma <- 2+4+6+8+10
      media <- soma/5
      escrevaL ("Primeiro número: 2")
      escrevaL ("Segundo número: 4")
      escrevaL ("Terceiro número: 6")
      escrevaL ("Quarto número: 8")
      escrevaL ("Quinto número: 10")
      escrevaL ("A soma entre eles é de: ", soma)
      escrevaL ("A média entre eles é de: ", media)
Fimalgoritmo
