Algoritmo "ExemploEntradaProcessamentoSaida"

Var
   num1: real
   num2: real
   resultado: real
Inicio
   escrevaL ("Digite o primeiro número: ")
   leia (num1)
   escrevaL ("Digite o segundo número: ")
   leia (num2)
   
   resultado <- num1*num2
   
   escreval ("Os números são: ")
   escreval ("O primeiro número digitado: ", num1)
   escreval ("O segundo número digitado: ", num2)
   escreval ("Resultado: ", resultado)

Fimalgoritmo