algoritmo "AtividadePratica1"

var

inicio
      escreval("Eu gosto de programar - literal de comprimento 21")
      escreval(123976.0, " - número real positivo com 1 casa decimal")
      escreval(-1.3849, " - número real negativo com 4 casas decimais")
      escreval(" - literal de comprimento 1")
      escreval("nome - literal de comprimento 4")
      escreval(0, " - número inteiro")
      escreval("@##$% - literal de comprimento 5")
fimalgoritmo
